# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

---
apiVersion: dnsentry.dac.nokia.com/v1alpha1
kind: DnsEntry
metadata:
  name: consul-dns-entry
spec:
  domainName: consul.company.com
  deploymentName: example-consul
  deploymentType: statefulsets