# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: consul-metrics
  annotations:
    kubernetes.io/ingress.class: "application"
spec:
  rules:
  - host: {{.Values.metricsDomainName}}
    http:
      paths:
      - backend:
          serviceName: example-consul-service
          servicePort: 8500
          