# permissions for end users to edit consuls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consul-editor-role
rules:
- apiGroups:
  - app.dac.nokia.com
  resources:
  - consuls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.dac.nokia.com
  resources:
  - consuls/status
  verbs:
  - get
