# permissions for end users to view consuls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consul-viewer-role
rules:
- apiGroups:
  - app.dac.nokia.com
  resources:
  - consuls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.dac.nokia.com
  resources:
  - consuls/status
  verbs:
  - get
