name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup operator-sdk Action
      uses: shivanshs9/setup-k8s-operator-sdk@v1.1.2
      with:
        version: "^0.18.0"
    - name: Build operator
      run: operator-sdk build consul-operator:test
      working-directory: ./consul-operator
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

#    - name: Build
#      run: go build -v ./...

    - name: Test
      run: go test -v ./...
